apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app
  labels:
    helm.sh/chart: test-app-0.1.0
    app.kubernetes.io/name: test-app
    app.kubernetes.io/instance: test-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm